<h1>Department</h1>
<span>Edit</span>
<form class="" action="<?php echo $block->urlSave(); ?>" method="post">
	<fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Edit Form') ?></span></legend><br>
        <div class="field required">
            <label for="Name" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Input') ?></span>
            </label>
            <div class="control">
                <input type="hidden"
                       name="id" value="<?= $block->Edit()->getEntity_id(); ?>" 
                       class="input-text">
            </div>
            <div class="control">
                <input type="text" id="number"
                       name="name" value="<?= $block->Edit()->getName(); ?>" 
                       class="input-text">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>


	<!-- <label>Name: </label><br>
	<input type="text" name="name"> -->
</form>

